---
- name: "Ping TCP para um IP (porta 22)"
  hosts: localhost
  gather_facts: false
  vars:
    # padrão; pode sobrescrever com: -e target_ip=1.2.3.4
    target_ip: "{{ lookup('env','TARGET_IP') | default('8.8.8.8') }}"

  tasks:
    - name: Testar conectividade TCP na porta 22
      ansible.builtin.wait_for:
        host: "{{ target_ip }}"
        port: 22
        timeout: 5
      register: ping_result

    - name: Exibir resultado
      debug:
        msg: "Conexão TCP para {{ target_ip }} bem-sucedida!"

    - name: Falhar se o host não respondeu na porta 22
      ansible.builtin.fail:
        msg: "Host {{ target_ip }} inacessível via TCP (porta 22)."
      when: not ping_result.elapsed or ping_result.failed is defined
